### ISSUE TITLE
undefined method `adapter_config' 

### ISSUE THREAD

**Issue by jackbit** [translationexchange/tml-ruby#3]
initializer:

```
Tml.configure do |config|
  config.application = {
    token: YOUR_APPLICATION_TOKEN,
  }

  config.cache = {
    enabled:    true,
    adapter:    'redis',
    host:       'localhost',
    port:       6379,
    password:   'password',
    namespace:  'translations'
  }
end
```

issue:

```
https://github.com/translationexchange/tml-ruby/blob/master/lib/tml/cache_adapters/redis.rb#L41

def initialize
    config = Tml.config.cache

    if config.adapter_config
      @cache = ::Redis.new(config.adapter_config)
    else
      config[:host] ||= 'localhost'
      config[:port] ||= 6379

      if config[:host].index(':')
        parts = config[:host].split(':')
        config[:host] = parts.first
        config[:port] = parts.last
      end

      @cache = ::Redis.new(config)
    end
  end

```

Error backtrace:

```
NoMethodError (undefined method `adapter_config' for #<Hash:0x007f839e31e060>):
  tml (4.4.7) lib/tml/cache_adapters/redis.rb:41:in `initialize'
  tml (4.4.7) lib/tml/cache.rb:45:in `new'
  tml (4.4.7) lib/tml/cache.rb:45:in `cache'
  tml (4.4.7) lib/tml/session.rb:52:in `init'
```

**Comment by berk** [comment]
Good catch. Should be fixed now.

https://github.com/translationexchange/tml-ruby/blob/master/lib/tml/cache_adapters/redis.rb
